"""add_panel_state_snapshot

Revision ID: 2a5e7c2778cd
Revises: 
Create Date: 2026-10-02 04:55:45.273980
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2a5e7c2778cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panel_state_snapshot',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('panel_state_snapshot')
    # ### end Alembic commands ###
